import {
  ArrowRightLeft,
  Blocks,
  BookOpen,
  Bot,
  CircleGauge,
  Code2,
  FileCode2,
  Gauge,
  Globe2,
  GraduationCap,
  Layers3,
  LayoutTemplate,
  Palette,
  PanelTop,
  PencilRuler,
  RefreshCw,
  Search,
  ShoppingCart,
  Sparkles,
  Store,
  Tags,
  UserCheck,
  UserRound,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { ServiceIcon } from "@/data/services";

export const serviceIconMap: Record<ServiceIcon, LucideIcon> = {
  layout: LayoutTemplate,
  wordpress: FileCode2,
  store: Store,
  learn: GraduationCap,
  cart: ShoppingCart,
  book: BookOpen,
  palette: Palette,
  tags: Tags,
  ruler: PencilRuler,
  plugin: Blocks,
  globe: Globe2,
  refresh: RefreshCw,
  transfer: ArrowRightLeft,
  wrench: Wrench,
  layers: Layers3,
  users: Users,
  developer: UserRound,
  specialist: UserCheck,
  sparkles: Sparkles,
  landing: PanelTop,
  gauge: Gauge,
  vitals: CircleGauge,
  code: Code2,
  bot: Bot,
  search: Search,
};
